### NumPy

#### 1.1 Основы

**Зачем нужен NumPy?**

Основное преимущество NumPy заключается в его **высокой производительности**.  Библиотека NumPy написана на языке C, что обеспечивает **значительное ускорение** операций по сравнению с выполнением аналогичных действий с использованием стандартных циклов Python. В области машинного обучения **постоянно возникает необходимость работать с векторами и матрицами**, и NumPy предоставляет для этого **структуру данных `ndarray`**, которая идеально подходит для эффективного представления и обработки многомерных массивов.

Массивы NumPy (`ndarray`) обладают важной особенностью: они могут хранить **только данные одного типа** (например, только целые числа `int` или только числа с плавающей точкой `float`).  Это ограничение компенсируется **существенным выигрышем в скорости выполнения операций**, поскольку NumPy может эффективно организовывать данные в памяти и использовать оптимизированные алгоритмы для их обработки.

**Создание массива NumPy**

Самый простой способ создать массив NumPy – это **преобразовать существующий список Python** в массив NumPy с помощью функции `np.array()`.

In [2]:
import numpy as np # NumPy принято сокращать как np для краткости
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array(python_list)

print(python_list)
print(numpy_array)
print(type(numpy_array))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


Ключевые характеристика массивов Numpy:     
1. __Однородность типа данных (dtype):__ Все элементы должны быть одного типа данных. Это может быть и __int__ и __float__ и __bool__ и многое другое. Проверть тип данных можно с помощью атрибута __.dtype__.
```python
        print(numpy_array.dtype)
```
2. __Размерность (ndim):__ Количество измерений массива. Вектор - одномерный массив (ndim = 1), матрица - двумерный (ndim = 2), и т.д. Размерность можно узнать с помощью атрибута **.ndim**.
```python
        print(numpy_arraay.ndim)
```
3. **Форма (shape):** Размер массива по каждому измерению. Форма возвращается в виде кортежа (tuple). Для одномерного массива форма - это количество элемнтов. Для двумерного - количество строк и столбцов. Форму можно узнать с помощью атрибута **.shape**.
```python 
        print(numpy_array.shape)
```

In [3]:
python_list_of_lists = [[1, 2, 3], [4, 5, 6]]

numpy_matrix = np.array(python_list_of_lists)

print(numpy_matrix, '\n', type(numpy_matrix), '\n', 
      numpy_matrix.dtype, '\n', numpy_matrix.ndim, '\n', numpy_matrix.shape)


[[1 2 3]
 [4 5 6]] 
 <class 'numpy.ndarray'> 
 int64 
 2 
 (2, 3)


----

#### 1.2 Базовые операции c векторами и матрицами

* **Поэлементные операции:**

   Операции NumPy применяются к каждому элементу массива **независимо**.  При сложении двух массивов **одинаковой формы**, элементы на **соответствующих позициях** складываются поэлементно.

In [4]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print('Сумма:', array1 + array2)
print('Разность', array2 - array1)
print('Произведение', array1 * array2)
print('Деление', array2 / array1) # при делении тип данных автоматически меняется на float

Сумма: [5 7 9]
Разность [3 3 3]
Произведение [ 4 10 18]
Деление [4.  2.5 2. ]


##### Векторы

1. **Векторные операции:**  Векторные операции – это операции, которые выполняются над массивами NumPy как над векторами.  Векторы, по сути, являются **одномерными массивами чисел**, над которыми можно производить различные базовые операции, включая вычисление **скалярного произведения**.

In [5]:
vector = np.array([1, 2, 3])
scalar = 2

scaled_vector = vector * scalar
print('Исходный вектор:', vector)
print('Скаляр:', scalar)
print('Вектор, умноженный на скаялр:', scaled_vector)

Исходный вектор: [1 2 3]
Скаляр: 2
Вектор, умноженный на скаялр: [2 4 6]


2. **Сложение и вычитание векторов:**  Сложение и вычитание векторов **возможно только** для векторов **одинаковой длины**.

In [6]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

print('Вектор 1:', vector1)
print('Вектор 2:', vector2)
print('Сумма векторов:', vector1 + vector2)
print('Разность векторов:', vector2 - vector1)

Вектор 1: [1 2 3]
Вектор 2: [4 5 6]
Сумма векторов: [5 7 9]
Разность векторов: [3 3 3]


3. **Скалярное произведение векторов (dot product):** Скалярное произведение двух векторов **одинаковой длины** – это **сумма произведений их соответствующих элементов**.

    * Способ первый: функция **`np.dot()`**
    * Способ второй: оператор **`@`**

In [7]:
vector3 = np.array([1, 2, 3])
vector4 = np.array([4, 5, 6])

print('Вектор 3:', vector3)
print('Вектор 4:', vector4)
print('Скаллярное произведение (np.dot):', np.dot(vector3, vector4))
print('Скалярное произведение (@):', vector3 @ vector4, ' - приоритетный вариант')

Вектор 3: [1 2 3]
Вектор 4: [4 5 6]
Скаллярное произведение (np.dot): 32
Скалярное произведение (@): 32  - приоритетный вариант


---

#### Матрицы
Матрицы в NumPy **представлены** как двумерные массивы (`ndarray` с `ndim=2`).

1. **Создание матриц:**

In [8]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
print('Матрица 1:\n', matrix1)

Матрица 1:
 [[1 2 3]
 [4 5 6]]


2. **Поэлементальные операции с матрицами:**

In [9]:
matrix2 = np.array([[7, 8, 9], [10, 11, 12]])

print('\nМатрица 1:\n', matrix1)
print('\nМатрица 2:\n', matrix2)
print('\nПоэлементальная сумма матриц:\n', matrix1 + matrix2)
print('\nПоэлементальная разность матриц:\n', matrix2 - matrix1)
print('\nПоэлементальное произведение матриц:\n', matrix1 * matrix2)
print('\nПоэлементальная деление матриц:\n', matrix2 / matrix1)


Матрица 1:
 [[1 2 3]
 [4 5 6]]

Матрица 2:
 [[ 7  8  9]
 [10 11 12]]

Поэлементальная сумма матриц:
 [[ 8 10 12]
 [14 16 18]]

Поэлементальная разность матриц:
 [[6 6 6]
 [6 6 6]]

Поэлементальное произведение матриц:
 [[ 7 16 27]
 [40 55 72]]

Поэлементальная деление матриц:
 [[7.  4.  3. ]
 [2.5 2.2 2. ]]


3. **Матричное умножение:**

   **Важно:** Матричное умножение – это **не** поэлементное умножение! Это принципиально иная операция, которая определяется правилами линейной алгебры.

   * **Правило матричного умножения:**  Для того чтобы матрицу A можно было умножить на матрицу B, **количество столбцов матрицы A должно быть равно количеству строк матрицы B**.  Если матрица A имеет размерность (m x n), а матрица B имеет размерность (n x p), то результатом матричного умножения будет матрица C размерности (m x p).

   * Элемент C[i, j] результирующей матрицы C вычисляется как **скалярное произведение i-й строки матрицы A и j-го столбца матрицы B**.

   * В NumPy для выполнения матричного умножения используются функция **`np.dot()`** и оператор **`@`**.

In [10]:
matrix3 = np.array([[1, 2], [3, 4]])
matrix4 = np.array([[5, 6, 7], [8, 9, 10]])

matrix_product = matrix3 @ matrix4

print('\nМатрица 1:\n', matrix3)
print('\nМатрица 2:\n', matrix4)
print('\nМатричное произведение:\n', matrix_product)



Матрица 1:
 [[1 2]
 [3 4]]

Матрица 2:
 [[ 5  6  7]
 [ 8  9 10]]

Матричное произведение:
 [[21 24 27]
 [47 54 61]]


4. **Транспонирование матрицы:**

   Транспонирование – это операция, которая **меняет местами** строки и столбцы матрицы.  В NumPy транспонированную матрицу можно получить, используя **атрибут `.T`**.

In [11]:
matrix5 = np.array([[1, 2, 3], [4, 5, 6]])
matrix5_transposed = matrix5.T
print('\nМатрица 5:\n', matrix5)
print('\nТранспонированная матрица:\n', matrix5_transposed)


Матрица 5:
 [[1 2 3]
 [4 5 6]]

Транспонированная матрица:
 [[1 4]
 [2 5]
 [3 6]]


___

#### **Индексация и срезы**


1. **Индексация одномерных массивов:**

In [12]:
vector = np.array([10, 20, 30, 40, 50])
 
first_element = vector[0] # Первый элемент
second_element = vector[1] # Второй элемент
last_element = vector[-1] # Последний элемент
penultimate_element = vector[-2] # Предпоследний элемент 

print('Исходный вектор:', vector)   
print('Первый элемент', first_element)
print('Второй элемент', second_element)
print('Последний элемент', last_element)
print('Предпоследний элемент', penultimate_element)

Исходный вектор: [10 20 30 40 50]
Первый элемент 10
Второй элемент 20
Последний элемент 50
Предпоследний элемент 40


2. **Индексация двумерных массивов (матриц):**

   В двумерных массивах, каждый элемент **определяется двумя индексами**: номером строки и номером столбца.  Индексация, как и в одномерных массивах, **начинается с 0**.

   Для доступа к конкретному элементу матрицы, необходимо указать **оба индекса через запятую** внутри квадратных скобок, в следующем порядке: `matrix[номер_строки, номер_столбца]`.

In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

element_0_0 = matrix[0, 0] # Элемент в 0-й строке и 0-м столбце
element_1_2 = matrix[1, 2] # Элемент в 1-й строке и 2-м столбце
element_2_1 = matrix[2, 1] # Элемент в 2-й строке и 1-и стобце
element_last_row_last_col = matrix[-1, -1] # Последний элемент

print("Исходная матрица:\n", matrix)
print("Элемент [0, 0]:", element_0_0)
print("Элемент [1, 2]:", element_1_2)
print("Элемент [2, 1]:", element_2_1)
print("Последний элемент [-, -]:", element_last_row_last_col)

Исходная матрица:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Элемент [0, 0]: 1
Элемент [1, 2]: 6
Элемент [2, 1]: 8
Последний элемент [-, -]: 9


3. **Срезы (slicing) одномерных массивов:**

   Срезы (slicing) позволяют **выделить диапазон элементов** из массива.  Для указания диапазона используется **синтаксис срезов**: `[start:stop:step]`.

In [14]:
vector_slice = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

slice_1_to_4 = vector_slice[1:5]    # Элементы с индексами 1, 2, 3, 4 (до 5, не включая 5)
slice_from_begin_to_3 = vector_slice[:4] # С начала до индекса 4 (не включая 4)
slice_from_5_to_end = vector_slice[5:]   # С индекса 5 до конца
slice_even_indices = vector_slice[::2]  # Каждый второй элемент (шаг 2)
slice_reverse = vector_slice[::-1]     # В обратном порядке (шаг -1)

print("Исходный вектор:", vector_slice)
print("Срез [1:5]:", slice_1_to_4)
print("Срез [:4]:", slice_from_begin_to_3)
print("Срез [5:]:", slice_from_5_to_end)
print("Срез [::2]:", slice_even_indices)
print("Срез [::-1]:", slice_reverse)

Исходный вектор: [ 10  20  30  40  50  60  70  80  90 100]
Срез [1:5]: [20 30 40 50]
Срез [:4]: [10 20 30 40]
Срез [5:]: [ 60  70  80  90 100]
Срез [::2]: [10 30 50 70 90]
Срез [::-1]: [100  90  80  70  60  50  40  30  20  10]


4. **Срезы матриц:**

   Для двумерных массивов (матриц) срезы применяются **отдельно для строк и для столбцов**, и указываются **через запятую**.  Общий синтаксис среза матрицы выглядит следующим образом:

   ```python
   matrix[срез_строки, срез_столбца]

In [15]:
matrix_slice = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

slice_rows_0_to_2 = matrix_slice[0:3, :]    # Строки с 0 по 2 (не включая 3), все столбцы (:)
slice_cols_1_to_3 = matrix_slice[:, 1:4]    # Все строки (:), столбцы с 1 по 3 (не включая 4)
slice_top_left_2x2 = matrix_slice[:2, :2]   # Верхний левый угол 2x2
slice_bottom_right_2x2 = matrix_slice[2:, 2:] # Нижний правый угол 2x2
slice_every_other_row_col = matrix_slice[::2, ::2] # Каждая вторая строка и каждый второй столбец

print("Исходная матрица:\n", matrix_slice)
print("\nСрез строк [0:3, :]:\n", slice_rows_0_to_2)
print("\nСрез столбцов [:, 1:4]:\n", slice_cols_1_to_3)
print("\nСрез верхний левый 2x2:\n", slice_top_left_2x2)
print("\nСрез нижний правый 2x2:\n", slice_bottom_right_2x2)
print("\nСрез каждая вторая строка/столбец:\n", slice_every_other_row_col)

Исходная матрица:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Срез строк [0:3, :]:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Срез столбцов [:, 1:4]:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]

Срез верхний левый 2x2:
 [[1 2]
 [5 6]]

Срез нижний правый 2x2:
 [[11 12]
 [15 16]]

Срез каждая вторая строка/столбец:
 [[ 1  3]
 [ 9 11]]


#### Изменение формы массивов

Основным инструментом для изменения формы массива является метод `.reshape()`.

**Важное правило при изменении формы:**  **Общее количество элементов в массиве должно оставаться неизменным!**  Если исходный массив содержал, например, 12 элементов, то после изменения формы он **должен по-прежнему содержать 12 элементов**.  Вы можете изменять количество строк и столбцов, но **произведение этих значений (общее количество элементов) должно оставаться прежним**.

1. **Преобразование одномерного массива в двумерный:**

In [17]:
vector_reshape = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Исходный вектор:\n", vector_reshape)
print("Форма исходного вектора:", vector_reshape.shape) # (12,)

# Мы можем преобразовать его в матрицу 3x4 (3 строки, 4 столбца), потому что 3 * 4 = 12:

matrix_reshaped_3x4 = vector_reshape.reshape((3, 4)) # Обрати внимание на двойные скобки!
print("\nМатрица 3x4:\n", matrix_reshaped_3x4)
print("Форма матрицы 3x4:", matrix_reshaped_3x4.shape) # (3, 4)

Исходный вектор:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Форма исходного вектора: (12,)

Матрица 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Форма матрицы 3x4: (3, 4)


2. **Преобразование двумерного массива в одномерный:**

   Возможно и обратное действие – "развернуть" матрицу (двумерный массив) в вектор (одномерный массив).  Рассмотрим, например, матрицу 3x4, созданную ранее:

In [18]:
print("\nИсходная матрица 3x4:\n", matrix_reshaped_3x4)
print("Форма исходной матрицы:", matrix_reshaped_3x4.shape) # (3, 4)

vector_reshaped_again = matrix_reshaped_3x4.reshape((12,)) # Или можно просто reshape(-1)
print("\nВектор из матрицы:\n", vector_reshaped_again)
print("Форма вектора:", vector_reshaped_again.shape) # (12,)


Исходная матрица 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Форма исходной матрицы: (3, 4)

Вектор из матрицы:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Форма вектора: (12,)


3. **Использование `-1` в `reshape()` для автоматического вычисления размера:**

   Когда вы используете значение `-1` в качестве одного из размеров в методе `.reshape()`, NumPy **автоматически вычисляет размер этого измерения**.  Расчет производится на основе **общего количества элементов в массиве** и размеров, указанных для других измерений.

   Это **очень удобная возможность**, которая позволяет вам:

   * **Избежать ручного расчета размера измерения:** Вам не нужно самостоятельно вычислять, каким должен быть размер измерения, чтобы общее количество элементов оставалось неизменным. NumPy сделает это за вас.
   * **Сделать код более гибким:**  Использование `-1` позволяет коду **адаптироваться к массивам с разным количеством элементов**, при условии, что общая размерность массива позволяет выполнить reshape.

In [19]:
print("\nИсходная матрица 3x4:\n", matrix_reshaped_3x4)
print("Форма исходной матрицы:", matrix_reshaped_3x4.shape) # (3, 4)

matrix_reshaped_auto_rows = matrix_reshaped_3x4.reshape((-1, 2)) # -1 для автоматического расчета строк, 2 столбца
print("\nМатрица с авто-строками и 2 столбцами:\n", matrix_reshaped_auto_rows)
print("Форма матрицы:", matrix_reshaped_auto_rows.shape) # (6, 2) - получилось 6 строк и 2 столбца


Исходная матрица 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Форма исходной матрицы: (3, 4)

Матрица с авто-строками и 2 столбцами:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Форма матрицы: (6, 2)


---

#### **Бродкастинг (транслирование)**

   Транслирование (broadcasting) – это **мощный механизм NumPy**, который позволяет выполнять **арифметические операции** над массивами **различных форм**, при условии, что эти формы **совместимы**.  На первый взгляд, это может показаться сложным, но на практике бродкастинг является **очень полезным и интуитивно понятным** инструментом.

**Правила транслирования:**

1. **Сравнение размерностей:**  При проверке совместимости, размерности массивов **сравниваются справа налево (от младших к старшим)**.

2. **Условия совместимости размерностей:** Две размерности считаются **совместимыми**, если выполняется **хотя бы одно** из следующих условий:
    * **Размерности равны.**
    * **Одна из размерностей равна 1.**

3. **Выравнивание размерностей:** Если массивы имеют **различное количество размерностей**, то к массиву с **меньшим количеством размерностей** **слева добавляются "единичные" размерности** до тех пор, пока количество размерностей не станет одинаковым.

1. **Скаялр и массив:**

In [21]:
scalar_broadcast = 2
vector_broadcast = np.array([1, 2, 3])
matrix_broadcast = np.array([[1, 2], [3, 4]])

vector_scaled_broadcast = vector_broadcast * scalar_broadcast
matrix_scaled_broadcast = matrix_broadcast * scalar_broadcast

print("Скаляр:", scalar_broadcast)
print("Вектор:\n", vector_broadcast)
print("Матрица:\n", matrix_broadcast)
print("\nВектор, умноженный на скаляр (транслирование):\n", vector_scaled_broadcast)
print("\nМатрица, умноженная на скаляр (транслирование):\n", matrix_scaled_broadcast)

Скаляр: 2
Вектор:
 [1 2 3]
Матрица:
 [[1 2]
 [3 4]]

Вектор, умноженный на скаляр (транслирование):
 [2 4 6]

Матрица, умноженная на скаляр (транслирование):
 [[2 4]
 [6 8]]


2. **Транслирование вектора и матрицы (транслирование по строкам):**

   Для того чтобы транслировать вектор **по столбцам** матрицы, необходимо **преобразовать вектор в вектор-столбец** с помощью метода `.reshape()`.

In [22]:
matrix_broadcast_2 = np.array([[1, 2, 3], [4, 5, 6]]) # Матрица 2x3
vector_col_broadcast = np.array([100, 200]).reshape((2, 1)) # Вектор-столбец (форма (2, 1))

matrix_plus_col = matrix_broadcast_2 + vector_col_broadcast

print("\nМатрица:\n", matrix_broadcast_2)
print("Вектор-столбец:\n", vector_col_broadcast)
print("\nМатрица + вектор-столбец (транслирование по столбцам):\n", matrix_plus_col)


Матрица:
 [[1 2 3]
 [4 5 6]]
Вектор-столбец:
 [[100]
 [200]]

Матрица + вектор-столбец (транслирование по столбцам):
 [[101 102 103]
 [204 205 206]]


   Здесь вектор-столбец `[[100], [200]]` **транслируется** и **"растягивается"** для соответствия каждому столбцу матрицы.  Это означает, что **вектор-столбец как бы "повторяется"** для каждого столбца матрицы, и затем **поэлементно прибавляется к каждому столбцу матрицы**.

   **Преимущества транслирования:**

   * **Краткость и лаконичность кода:**  Транслирование позволяет **избежать написания явных циклов** для выполнения операций между массивами разных форм.  Код становится **значительно более компактным, выразительным и легким для чтения**.

   * **Высокая эффективность:**  Операции транслирования в NumPy **выполняются очень эффективно**, часто **существенно быстрее**, чем если бы вы реализовывали аналогичные операции, используя циклы на чистом Python.  Это обусловлено тем, что NumPy использует оптимизированный, векторизованный код на C/Fortran для реализации бродкастинга.

---

Зачем нужны универсальные функции (ufuncs)?

**Производительность (Скорость):**  Универсальные функции (ufuncs) в NumPy написаны на языке C и **скомпилированы**, что обеспечивает **значительное ускорение** выполнения операций.  Ufuncs работают **на порядки быстрее**, чем реализация аналогичных операций на чистом Python с использованием циклов `for`.  В таких областях, как машинное обучение, где **скорость обработки данных имеет критическое значение**, ufuncs являются **незаменимым инструментом** для повышения эффективности вычислений.

**Удобство использования (Лаконичность кода):**  Ufuncs делают код NumPy **более лаконичным и читаемым**.  Вместо того чтобы писать развернутые циклы для обработки каждого элемента массива, вы можете **просто вызвать ufunc и передать ей массив целиком**.  Это значительно упрощает код и уменьшает вероятность ошибок.

**Векторизация вычислений:**  Ufuncs **обеспечивают векторизацию вычислений**.  **Векторизация** – это парадигма программирования, в которой операции применяются **сразу к целым массивам данных**, а не к отдельным элементам по отдельности.  **Векторизованный код**, использующий ufuncs, обычно **работает гораздо быстрее и эффективнее**, чем не векторизованный код, основанный на циклах Python.

**Типы универсальных функций (ufuncs):**

Универсальные функции (ufuncs) NumPy подразделяются на различные типы в зависимости от количества входных массивов и выполняемых операций.

* **Унарные ufuncs:**  Унарные ufuncs выполняют операции **над одним входным массивом**.  Примеры унарных ufuncs:

    * **Математические ufuncs:**  `np.abs()`, `np.sqrt()`, `np.exp()`, `np.log()`, `np.sin()`, `np.cos()`, `np.tan()`, `np.floor()`, `np.ceil()`, `np.round()` и многие другие **математические функции**.

    * **Логические ufuncs:**  `np.logical_not()` (логическое "НЕ").

* **Бинарные ufuncs:** Бинарные ufuncs выполняют операции **между двумя входными массивами (поэлементно)**.  Примеры бинарных ufuncs:

    * **Арифметические ufuncs:**  `np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()`, `np.power()`, `np.mod()` (операции сложения, вычитания, умножения, деления, возведения в степень, взятия остатка от деления).  **Обратите внимание:**  **Арифметические операторы Python** `+`, `-`, `*`, `/`, `**`, `%` – это **также ufuncs в NumPy**!  Они представляют собой **более "синтаксически удобные" (syntactic sugar)** версии соответствующих функций `np.add()`, `np.subtract()` и т.д.

    * **Логические ufuncs:**  `np.logical_and()`, `np.logical_or()`, `np.logical_xor()`, `np.equal()`, `np.not_equal()`, `np.less()`, `np.greater()`, `np.less_equal()`, `np.greater_equal()` (логическое "И", "ИЛИ", "ИСКЛЮЧАЮЩЕЕ ИЛИ", "равно", "не равно", "меньше", "больше", "меньше или равно", "больше или равно").

    * **Битовые ufuncs:**  `np.bitwise_and()`, `np.bitwise_or()`, `np.bitwise_xor()`, `np.bitwise_not()` (побитовые "И", "ИЛИ", "ИСКЛЮЧАЮЩЕЕ ИЛИ", "НЕ").

1. **Унарные функици:**

In [24]:
array_ufunc = np.array([-1, 2, -3, 4, -5])

abs_array = np.abs(array_ufunc) # Модуль каждого элемента
sqrt_array = np.sqrt(abs_array) # Квадратный корень из модуля  
exp_array = np.exp(array_ufunc) # Экспонента каждого элемента
sin_array = np.sin(array_ufunc) # Синус каждого элемента
rounded_array = np.round(array_ufunc, decimals=1) # Округление до 1 знака после запятой

print("Исходный массив:\n", array_ufunc)
print("\nМодуль (np.abs):\n", abs_array)
print("\nКвадратный корень (np.sqrt):\n", sqrt_array)
print("\nЭкспонента (np.exp):\n", exp_array)
print("\nСинус (np.sin):\n", sin_array)
print("\nОкругление (np.round):\n", rounded_array)

Исходный массив:
 [-1  2 -3  4 -5]

Модуль (np.abs):
 [1 2 3 4 5]

Квадратный корень (np.sqrt):
 [1.         1.41421356 1.73205081 2.         2.23606798]

Экспонента (np.exp):
 [3.67879441e-01 7.38905610e+00 4.97870684e-02 5.45981500e+01
 6.73794700e-03]

Синус (np.sin):
 [-0.84147098  0.90929743 -0.14112001 -0.7568025   0.95892427]

Округление (np.round):
 [-1  2 -3  4 -5]


2. **Бинарные ufuncs:**

In [25]:
array_ufunc_1 = np.array([1, 2, 3, 4, 5])
array_ufunc_2 = np.array([6, 7, 8, 9, 10])

sum_arrays = np.add(array_ufunc_1, array_ufunc_2) # Поэлементное сложение
product_arrays = np.multiply(array_ufunc_1, array_ufunc_2) # Поэлементное умножение
power_arrays = np.power(array_ufunc_1, 2) # Возведение в степень (здесь второй массив - скаляр 2, транслируется)
greater_arrays = np.greater(array_ufunc_2, array_ufunc_1) # Поэлементное сравнение "больше" (возвращает массив boolean)

print("\nМассив 1:\n", array_ufunc_1)
print("\nМассив 2:\n", array_ufunc_2)
print("\nСумма (np.add):\n", sum_arrays)
print("\nПроизведение (np.multiply):\n", product_arrays)
print("\nСтепень (np.power):\n", power_arrays)
print("\nСравнение 'больше' (np.greater):\n", greater_arrays)


Массив 1:
 [1 2 3 4 5]

Массив 2:
 [ 6  7  8  9 10]

Сумма (np.add):
 [ 7  9 11 13 15]

Произведение (np.multiply):
 [ 6 14 24 36 50]

Степень (np.power):
 [ 1  4  9 16 25]

Сравнение 'больше' (np.greater):
 [ True  True  True  True  True]


---

#### **Генерация случайных чисел**

   В машинном обучении **случайные числа играют исключительно важную роль**.  Они необходимы во множестве задач и алгоритмов.  Вот лишь несколько **ключевых примеров**, иллюстрирующих их применение:

   * **Инициализация весов нейронных сетей:**  На начальном этапе обучения, веса нейронных сетей **инициализируются случайными значениями**.  **Правильная случайная инициализация** является **критически важной** для обеспечения успешного и эффективного обучения модели.

   * **Разбиение данных на обучающую и тестовую выборки:**  Для **объективной оценки качества** модели машинного обучения, данные **случайным образом разделяются** на две (или более) части: обучающую выборку (для обучения модели) и тестовую выборку (для оценки ее обобщающей способности).

   * **Перемешивание данных (shuffling):**  Перед началом обучения, данные часто **перемешивают в случайном порядке (shuffling)**.  Это помогает **избежать смещений** в данных и **улучшить процесс обучения**, обеспечивая более равномерное представление различных классов и паттернов.

   * **Алгоритмы случайного поиска (Random Search):**  Для **оптимизации гиперпараметров моделей машинного обучения**, часто используются **алгоритмы случайного поиска**.  Эти алгоритмы исследуют пространство параметров, **случайно перебирая различные комбинации** гиперпараметров в поисках оптимальной конфигурации.

   * **Моделирование случайных процессов:**  В ряде задач машинного обучения возникает необходимость **моделировать случайные процессы**.  Это может включать в себя **генерацию случайных траекторий**, **создание случайных выборок** для имитационного моделирования, или **моделирование стохастических систем**.

   Для обеспечения всего этого функционала, NumPy предоставляет **мощный подмодуль `numpy.random`**, который содержит **обширный набор инструментов** для генерации **разнообразных случайных чисел** и **случайных выборок** из различных распределений.

1. `np.random.rand(d0, d1, ..., dn)`:  Генерирует массив случайных **чисел** с **равномерным** распределением в **диапазоне** `[0, 1)`.

In [26]:
random_array_rand = np.random.rand(3, 2) # Матрица 3x2 случайных чиесл от 0 до 1
print('Массив rand (3x2):\n', random_array_rand)

Массив rand (3x2):
 [[0.7535137  0.49705976]
 [0.61961096 0.50667011]
 [0.61975065 0.37193291]]


2. `np.random.randn(d0, d1, ..., dn)`:  Генерирует массив случайных чисел из **стандартного нормального распределения** (среднее **0**, стандартное отклонение **1**).

In [27]:
random_array_randn = np.random.randn(2, 4) # Матрица 2x4 случанйх чисел из нормального распределения
print('Массив randn (2x4):\n', random_array_randn)

Массив randn (2x4):
 [[ 1.09910184  0.17744925  0.30546945 -1.93231615]
 [ 0.10794992 -2.06874587  0.26502948 -0.42839157]]


3. `np.random.randint(low, high=None, size=None, dtype=int)`:  Генерирует массив **целых** случайных чисел, **равномерно распределенных** в дискретном диапазоне `[low, high)`.  **Если параметр `high` не указан**, диапазон генерируется как `[0, low)`.  Параметр `size` задает **форму** выходного массива.

In [28]:
random_integers_1_10 = np.random.randint(1, 11, size=5) # 5 случайных целых чисел от 1 до 10
random_integers_0_5_matrix = np.random.randint(0, 6, size=(2,3)) # Матрица 2x3 случайных чисел от 0 до 5

print("\nЦелые числа randint [1, 11) (5):\n", random_integers_1_10)
print("\nЦелые числа randint [0, 6) (2x3):\n", random_integers_0_5_matrix)


Целые числа randint [1, 11) (5):
 [ 5 10  5  4  6]

Целые числа randint [0, 6) (2x3):
 [[1 3 4]
 [4 3 1]]


4. `np.random.random(size=None)`:  **Аналогична** функции `np.random.rand()`, но **принимает размер массива** в виде **кортежа** в аргументе `size`, а **не** как отдельные аргументы размерностей.  **Если `size=None`**, функция **возвращает одно случайное число** (скаляр).

In [29]:
random_array_random = np.random.random((4, 2)) # Матрица 4x2 случайных чисел от 0 до 1
single_random_number = np.random.random() # Одно случайное число от 0 до 1
print("\nМассив random (4x2):\n", random_array_random)
print("\nСлучайное число random (одно):\n", single_random_number)


Массив random (4x2):
 [[0.28681719 0.79014476]
 [0.04492278 0.06153608]
 [0.3060504  0.44309582]
 [0.30205319 0.82298068]]

Случайное число random (одно):
 0.9070447487515539


5. `np.random.choice(a, size=None, replace=True, p=None)`:  Генерирует **случайную выборку** из **заданного массива `a`**.

    * `a` – **Исходный массив**, из которого производится выборка.  Может быть массивом NumPy или **целым числом**.  **Если `a` – целое число**, выборка будет производиться из массива, сгенерированного как `np.arange(a)` (последовательность целых чисел от 0 до `a-1`).

    * `size` –  **Форма** (размерность) **выходного массива**.

    * `replace=True` –  **Выборка с возвращением**.  Если `replace=True`, **один и тот же элемент** из массива `a` **может быть выбран несколько раз** в выходной выборке.  `replace=False` – **Выборка без возвращения**.  В этом случае, каждый элемент из `a` может быть выбран **не более одного раза**.

    * `p` –  **Вероятности выбора** каждого элемента из массива `a`.  Должен быть **одномерный массив** той же длины, что и `a`, содержащий **вероятности** (от 0 до 1) для каждого элемента.  **Если параметр `p` не указан**, то **вероятности считаются равномерными** для всех элементов массива `a`.

In [30]:
data_for_choice = np.array(['a', 'b', 'c', 'd', 'e'])
random_choice_1 = np.random.choice(data_for_choice) # Случайный выбор одного элемента из массива
random_choice_5 = np.random.choice(data_for_choice, size=5) # 5 случайных выборок с возвращением
random_choice_3_no_replace = np.random.choice(data_for_choice, size=3, replace=False) # 3 случайных выбора без возвращения
probabilities = [0.1, 0.2, 0.3, 0.25, 0.15] # Вероятности для каждого элемента
random_choice_weighted = np.random.choice(data_for_choice, size=5, p=probabilities) # Взвешенная случайная выборка

print("\nМассив для выбора:\n", data_for_choice)
print("\nСлучайный выбор (один):\n", random_choice_1)
print("\nСлучайный выбор (5 с возвращением):\n", random_choice_5)
print("\nСлучайный выбор (3 без возвращения):\n", random_choice_3_no_replace)
print("\nВзвешенный случайный выбор (5):\n", random_choice_weighted)


Массив для выбора:
 ['a' 'b' 'c' 'd' 'e']

Случайный выбор (один):
 a

Случайный выбор (5 с возвращением):
 ['c' 'e' 'd' 'c' 'c']

Случайный выбор (3 без возвращения):
 ['e' 'b' 'd']

Взвешенный случайный выбор (5):
 ['e' 'e' 'c' 'c' 'c']


`np.random.seed(seed=None)`:

   **Фиксация "зерна" генератора случайных чисел.**  Это **ключевой инструмент для обеспечения воспроизводимости результатов**, которые зависят от случайной генерации чисел.

   **Важность воспроизводимости:**  В научных исследованиях, машинном обучении и многих других областях **воспроизводимость экспериментов и результатов является крайне важной**.  Когда вы используете случайные числа в своем коде, результаты могут меняться при каждом запуске, если не контролировать генерацию случайных чисел.  `np.random.seed()` позволяет **зафиксировать начальную точку (зерно)** для генератора псевдослучайных чисел, делая последовательность случайных чисел **детерминированной и воспроизводимой**.

   **Как работает `np.random.seed()`:**  Если вы **установите одно и то же значение параметра `seed`** перед генерацией случайных чисел, NumPy будет **использовать это значение в качестве "зерна"**.  В результате, при каждом запуске кода с **одним и тем же значением `seed`**, вы будете получать **абсолютно идентичную последовательность случайных чисел**.

   **Если `seed=None` (или параметр `seed` не указан)** при вызове `np.random.seed()`, NumPy будет **использовать "системное время" в качестве зерна**.  Поскольку "системное время" меняется при каждом запуске программы, **последовательность случайных чисел будет разной при каждом запуске кода** в этом случае, что подходит для ситуаций, когда воспроизводимость не требуется, и нужна именно случайность.

In [31]:
np.random.seed(42) # Фиксируем зерно 42
random_array_seed_1 = np.random.rand(2, 2)
np.random.seed(42) # Снова фиксируем зерно 42 (перед второй генерацией)
random_array_seed_2 = np.random.rand(2, 2)

print("\nМассив 1 с seed=42:\n", random_array_seed_1)
print("\nМассив 2 с seed=42:\n", random_array_seed_2) # Массивы будут идентичны!

np.random.seed(None) # Снимаем фиксацию зерна (или можно просто не вызывать seed())
random_array_no_seed = np.random.rand(2, 2)
print("\nМассив без seed (каждый раз разный):\n", random_array_no_seed) # Массив будет меняться при каждом запуске


Массив 1 с seed=42:
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]]

Массив 2 с seed=42:
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]]

Массив без seed (каждый раз разный):
 [[0.51942478 0.70666025]
 [0.26545324 0.18718344]]
