## Часть 1: Основы программирования и анализа данных

### 1. NumPy

#### 1.1 Основы

Зачем нужен NumPy - он написан на C, что делает его операции очень быстрыми по сравнению с обычными циклами в python. В ml Постоянно надо работаеть с векторами и матрицами, а numpy предоставляет структуру данных 'ndarray', Которая идеально подходит для работы с векторами и матрицами. Массивы numpy позволяют работать только с данными одного типа (int или float), но зато мы получаем куда большую скорость выполнения.

Создаём массив NumPy
Самый просто способ - это преобразовать обычный список python в массив numpy с помошью функции np.array()

In [2]:
import numpy as np # NumPy принято сокращать как np для краткости
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array(python_list)

print(python_list)
print(numpy_array)
print(type(numpy_array))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


Ключевые характеристика массивов Numpy:     
1. __Однородность типа данных (dtype):__ Все элементы должны быть одного типа данных. Это может быть и __int__ и __float__ и __bool__ и многое другое. Проверть тип данных можно с помощью атрибута __.dtype__.
```python
        print(numpy_array.dtype)
```
2. __Размерность (ndim):__ Количество измерений массива. Вектор - одномерный массив (ndim = 1), матрица - двумерный (ndim = 2), и т.д. Размерность можно узнать с помощью атрибута **.ndim**.
```python
        print(numpy_arraay.ndim)
```
3. **Форма (shape):** Размер массива по каждому измерению. Форма возвращается в виде кортежа (tuple). Для одномерного массива форма - это количество элемнтов. Для двумерного - количество строк и столбцов. Форму можно узнать с помощью атрибута **.shape**.
```python 
        print(numpy_array.shape)
```

In [3]:
python_list_of_lists = [[1, 2, 3], [4, 5, 6]]

numpy_matrix = np.array(python_list_of_lists)

print(numpy_matrix, '\n', type(numpy_matrix), '\n', 
      numpy_matrix.dtype, '\n', numpy_matrix.ndim, '\n', numpy_matrix.shape)


[[1 2 3]
 [4 5 6]] 
 <class 'numpy.ndarray'> 
 int64 
 2 
 (2, 3)


----

#### 1.2 Базовые операции c векторами и матрицами

* **Поэлементные операции:** операции применяются к каждому элементу массива независимо от других элементов. Если сложить два массива одинаковой формы, сложатся элементы на одних и тех же позициях.

In [4]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print('Сумма:', array1 + array2)
print('Разность', array2 - array1)
print('Произведение', array1 * array2)
print('Деление', array2 / array1) # при делении тип данных автоматически меняется на float

Сумма: [5 7 9]
Разность [3 3 3]
Произведение [ 4 10 18]
Деление [4.  2.5 2. ]


##### Векторы
1. **Векторные операции:** это операции, которые выполняются над массивами как над векторами. Векторы - это по сути одномерные массивы чисел, над которыми можно выполнять базовые операции и находить их **скалярное произведение**.

In [5]:
vector = np.array([1, 2, 3])
scalar = 2

scaled_vector = vector * scalar
print('Исходный вектор:', vector)
print('Скаляр:', scalar)
print('Вектор, умноженный на скаялр:', scaled_vector)

Исходный вектор: [1 2 3]
Скаляр: 2
Вектор, умноженный на скаялр: [2 4 6]


2. **Сложение и вычитание векторов:** Складывать и вычитать векторы млжно только **одинаковой длины**.

In [6]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

print('Вектор 1:', vector1)
print('Вектор 2:', vector2)
print('Сумма векторов:', vector1 + vector2)
print('Разность векторов:', vector2 - vector1)

Вектор 1: [1 2 3]
Вектор 2: [4 5 6]
Сумма векторов: [5 7 9]
Разность векторов: [3 3 3]


3. **Скалярное произведение векторов (dot product):** Скалярное проихведение двух векторов одинаковой длины - это **сумма произведений их соответсвующих элементов**
    * Способ первый - функция **np.dot()**
    * Способ второй - оператор **@**

In [7]:
vector3 = np.array([1, 2, 3])
vector4 = np.array([4, 5, 6])

print('Вектор 3:', vector3)
print('Вектор 4:', vector4)
print('Скаллярное произведение (np.dot):', np.dot(vector3, vector4))
print('Скалярное произведение (@):', vector3 @ vector4, ' - приоритетный вариант')


Вектор 3: [1 2 3]
Вектор 4: [4 5 6]
Скаллярное произведение (np.dot): 32
Скалярное произведение (@): 32  - приоритетный вариант


Рачситаем  скалярное произведение вручную и сравним: (1x4) + (2x5) + (3x6) = 32

##### Матрицы
Матрицы в Numpy представляются как двумерные массивы (ndarray с ndim=2)
1. **Создание матриц:**

In [8]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
print('Матрица 1:\n', matrix1)

Матрица 1:
 [[1 2 3]
 [4 5 6]]


2. **Поэлементальные операции с матрицами**

In [9]:
matrix2 = np.array([[7, 8, 9], [10, 11, 12]])

print('\nМатрица 1:\n', matrix1)
print('\nМатрица 2:\n', matrix2)
print('\nПоэлементальная сумма матриц:\n', matrix1 + matrix2)
print('\nПоэлементальная разность матриц:\n', matrix2 - matrix1)
print('\nПоэлементальное произведение матриц:\n', matrix1 * matrix2)
print('\nПоэлементальная деление матриц:\n', matrix2 / matrix1)


Матрица 1:
 [[1 2 3]
 [4 5 6]]

Матрица 2:
 [[ 7  8  9]
 [10 11 12]]

Поэлементальная сумма матриц:
 [[ 8 10 12]
 [14 16 18]]

Поэлементальная разность матриц:
 [[6 6 6]
 [6 6 6]]

Поэлементальное произведение матриц:
 [[ 7 16 27]
 [40 55 72]]

Поэлементальная деление матриц:
 [[7.  4.  3. ]
 [2.5 2.2 2. ]]


3. **Матричное умножение:**         
Матричное умножение - это не поэлементальное умножение! Это совсем другая операция которая определена правилами линейной алгебры.

* **Правило матрицчного умножения:** Чтобы матрицу A можно было умножить на матрицу B, **количество столбцов матрицы A должно быть равно количеству строк матрицы B.** Если матрица A имеет форму (m x n), а матрица B имеет форму (n x p), то результатом матричного уможения будет матрица C формы (m x p),     
* Элемент C[i, j] вычисляется как **скалярное произведение i-й строки матрицы A и j-го столбца матрицы B.**
* В NumPy для матричного умножения также используется функкция np.dot() или оператор @

In [10]:
matrix3 = np.array([[1, 2], [3, 4]])
matrix4 = np.array([[5, 6, 7], [8, 9, 10]])

matrix_product = matrix3 @ matrix4

print('\nМатрица 1:\n', matrix3)
print('\nМатрица 2:\n', matrix4)
print('\nМатричное произведение:\n', matrix_product)



Матрица 1:
 [[1 2]
 [3 4]]

Матрица 2:
 [[ 5  6  7]
 [ 8  9 10]]

Матричное произведение:
 [[21 24 27]
 [47 54 61]]


4. **Транспонирование матрицы:**        
Транспонирование - это операция которая меняет местами строки и столбцы матрицы. В NumPy транспонированную матрицу можно получить с помощью атрибута .T .

In [11]:
matrix5 = np.array([[1, 2, 3], [4, 5, 6]])
matrix5_transposed = matrix5.T
print('\nМатрица 5:\n', matrix5)
print('\nТранспонированная матрица:\n', matrix5_transposed)


Матрица 5:
 [[1 2 3]
 [4 5 6]]

Транспонированная матрица:
 [[1 4]
 [2 5]
 [3 6]]


**Индексация и срезы**


1.Индексация одномерных массивов

In [12]:
vector = np.array([10, 20, 30, 40, 50])
 
first_element = vector[0] # Первый элемент
second_element = vector[1] # Второй элемент
last_element = vector[-1] # Последний элемент
penultimate_element = vector[-2] # Предпоследний элемент 

print('Исходный вектор:', vector)   
print('Первый элемент', first_element)
print('Второй элемент', second_element)
print('Последний элемент', last_element)
print('Предпоследний элемент', penultimate_element)

Исходный вектор: [10 20 30 40 50]
Первый элемент 10
Второй элемент 20
Последний элемент 50
Предпоследний элемент 40


2. Инедксация двумерных массивов (матриц)       
В двумерном массиве у каждого элемнта есть два индекса: номер строки и номер столбца, также начиная с 0. Чтобы получить доступ к элементу, нужно указать оба индекса через запятую в квадратных скобках: matrix[номер_строки, номер_столбца]

In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

element_0_0 = matrix[0, 0] # Элемент в 0-й строке и 0-м столбце
element_1_2 = matrix[1, 2] # Элемент в 1-й строке и 2-м столбце
element_2_1 = matrix[2, 1] # Элемент в 2-й строке и 1-и стобце
element_last_row_last_col = matrix[-1, -1] # Последний элемент

print("Исходная матрица:\n", matrix)
print("Элемент [0, 0]:", element_0_0)
print("Элемент [1, 2]:", element_1_2)
print("Элемент [2, 1]:", element_2_1)
print("Последний элемент [-, -]:", element_last_row_last_col)

Исходная матрица:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Элемент [0, 0]: 1
Элемент [1, 2]: 6
Элемент [2, 1]: 8
Последний элемент [-, -]: 9


3. Срезы (slicing) одномерных массивов:
Срезы позволяют выделить диапозон из массива. Для этого используются синтаксис [start:stop:step]

In [14]:
vector_slice = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

slice_1_to_4 = vector_slice[1:5]    # Элементы с индексами 1, 2, 3, 4 (до 5, не включая 5)
slice_from_begin_to_3 = vector_slice[:4] # С начала до индекса 4 (не включая 4)
slice_from_5_to_end = vector_slice[5:]   # С индекса 5 до конца
slice_even_indices = vector_slice[::2]  # Каждый второй элемент (шаг 2)
slice_reverse = vector_slice[::-1]     # В обратном порядке (шаг -1)

print("Исходный вектор:", vector_slice)
print("Срез [1:5]:", slice_1_to_4)
print("Срез [:4]:", slice_from_begin_to_3)
print("Срез [5:]:", slice_from_5_to_end)
print("Срез [::2]:", slice_even_indices)
print("Срез [::-1]:", slice_reverse)

Исходный вектор: [ 10  20  30  40  50  60  70  80  90 100]
Срез [1:5]: [20 30 40 50]
Срез [:4]: [10 20 30 40]
Срез [5:]: [ 60  70  80  90 100]
Срез [::2]: [10 30 50 70 90]
Срез [::-1]: [100  90  80  70  60  50  40  30  20  10]


4. Срезы матриц:        
Для двумерных массивов применяются отдельно для строк и для стобцов, через запятую: ```matrix[срез_строки, срез_стобца]```.

In [15]:
matrix_slice = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

slice_rows_0_to_2 = matrix_slice[0:3, :]    # Строки с 0 по 2 (не включая 3), все столбцы (:)
slice_cols_1_to_3 = matrix_slice[:, 1:4]    # Все строки (:), столбцы с 1 по 3 (не включая 4)
slice_top_left_2x2 = matrix_slice[:2, :2]   # Верхний левый угол 2x2
slice_bottom_right_2x2 = matrix_slice[2:, 2:] # Нижний правый угол 2x2
slice_every_other_row_col = matrix_slice[::2, ::2] # Каждая вторая строка и каждый второй столбец

print("Исходная матрица:\n", matrix_slice)
print("\nСрез строк [0:3, :]:\n", slice_rows_0_to_2)
print("\nСрез столбцов [:, 1:4]:\n", slice_cols_1_to_3)
print("\nСрез верхний левый 2x2:\n", slice_top_left_2x2)
print("\nСрез нижний правый 2x2:\n", slice_bottom_right_2x2)
print("\nСрез каждая вторая строка/столбец:\n", slice_every_other_row_col)

Исходная матрица:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Срез строк [0:3, :]:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Срез столбцов [:, 1:4]:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]

Срез верхний левый 2x2:
 [[1 2]
 [5 6]]

Срез нижний правый 2x2:
 [[11 12]
 [15 16]]

Срез каждая вторая строка/столбец:
 [[ 1  3]
 [ 9 11]]


In [16]:
my_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

slice_second_col = my_matrix[:, 1]
slice_third_row = my_matrix[2, :]
slice_center = my_matrix[1:3, 1:3]
other = my_matrix[1:-1, 1:-1]

print('\nИзначальная матрица\n', my_matrix)
print('\nВторой столбцец\n', slice_second_col, '\n', slice_second_col.shape)
print('\nТретья строка\n', slice_third_row, '\n', slice_third_row.shape)
print('\nЦентральная подматрица\n', slice_center, '\n', slice_center.shape)
print('\nВсе кроме первой и последней\n', other, '\n', other.shape)


Изначальная матрица
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Второй столбцец
 [ 2  6 10 14] 
 (4,)

Третья строка
 [ 9 10 11 12] 
 (4,)

Центральная подматрица
 [[ 6  7]
 [10 11]] 
 (2, 2)

Все кроме первой и последней
 [[ 6  7]
 [10 11]] 
 (2, 2)


Основной инструмент для изменения формы массива - это метод .reshape().

Важное правило при изменении формы: Общее количество элементов в массиве должно оставаться неизменным! Если у тебя был массив из 12 элементов, то после изменения формы он должен по-прежнему содержать 12 элементов. Ты можешь изменить количество строк и столбцов, но их произведение должно остаться прежним.

1. Преобразование одномерного массива в двумерный:

In [17]:
vector_reshape = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Исходный вектор:\n", vector_reshape)
print("Форма исходного вектора:", vector_reshape.shape) # (12,)

# Мы можем преобразовать его в матрицу 3x4 (3 строки, 4 столбца), потому что 3 * 4 = 12:

matrix_reshaped_3x4 = vector_reshape.reshape((3, 4)) # Обрати внимание на двойные скобки!
print("\nМатрица 3x4:\n", matrix_reshaped_3x4)
print("Форма матрицы 3x4:", matrix_reshaped_3x4.shape) # (3, 4)

Исходный вектор:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Форма исходного вектора: (12,)

Матрица 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Форма матрицы 3x4: (3, 4)


2. Преобразование двумерного массива в одномерный:
Можно и наоборот - "развернуть" матрицу в вектор. Например, возьмем матрицу 3x4, которую мы только что создали:

In [18]:
print("\nИсходная матрица 3x4:\n", matrix_reshaped_3x4)
print("Форма исходной матрицы:", matrix_reshaped_3x4.shape) # (3, 4)

vector_reshaped_again = matrix_reshaped_3x4.reshape((12,)) # Или можно просто reshape(-1)
print("\nВектор из матрицы:\n", vector_reshaped_again)
print("Форма вектора:", vector_reshaped_again.shape) # (12,)


Исходная матрица 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Форма исходной матрицы: (3, 4)

Вектор из матрицы:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Форма вектора: (12,)


3. Использование -1 в reshape() для автоматического вычисления размера:
Когда ты используешь -1 в качестве одного из размеров в reshape(), NumPy автоматически вычисляет размер этого измерения, исходя из общего количества элементов и размеров других измерений. Это очень удобно!

In [19]:
print("\nИсходная матрица 3x4:\n", matrix_reshaped_3x4)
print("Форма исходной матрицы:", matrix_reshaped_3x4.shape) # (3, 4)

matrix_reshaped_auto_rows = matrix_reshaped_3x4.reshape((-1, 2)) # -1 для автоматического расчета строк, 2 столбца
print("\nМатрица с авто-строками и 2 столбцами:\n", matrix_reshaped_auto_rows)
print("Форма матрицы:", matrix_reshaped_auto_rows.shape) # (6, 2) - получилось 6 строк и 2 столбца


Исходная матрица 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Форма исходной матрицы: (3, 4)

Матрица с авто-строками и 2 столбцами:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Форма матрицы: (6, 2)


In [20]:
my_matrix_2x6 = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

matrix_3x4 = my_matrix_2x6.reshape((3, 4))
matrix_6x2 = my_matrix_2x6.reshape((6, 2))
matrix_to_vector = my_matrix_2x6.reshape((12,))
matrix_12x1 = my_matrix_2x6.reshape((12,1))
matrix_1x12 = my_matrix_2x6.reshape((1, 12))

print(matrix_3x4, '\n')
print(matrix_6x2, '\n')
print(matrix_to_vector, '\n')
print(matrix_12x1, '\n')
print(matrix_1x12, '\n')


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] 

[[ 1  2  3  4  5  6  7  8  9 10 11 12]] 



**Broadcasting (транслирование)**       
 Транслирование – это как волшебство NumPy, которое позволяет выполнять арифметические операции над массивами разных форм, если эти формы совместимы. Звучит немного запутанно, но на самом деле это очень полезный и интуитивно понятный механизм.

**Правила трансилирования**
1. Размерности сравниваются справа налево
2. Две размерности совместимы если:
    * Они равны.
    * Одна из них равна 1.
3. Если кол-во размерностей различается, то к массиву с меньшим количество размерностей слева добавляются "единичные" размерности.

1. Скаялр и массив:

In [21]:
scalar_broadcast = 2
vector_broadcast = np.array([1, 2, 3])
matrix_broadcast = np.array([[1, 2], [3, 4]])

vector_scaled_broadcast = vector_broadcast * scalar_broadcast
matrix_scaled_broadcast = matrix_broadcast * scalar_broadcast

print("Скаляр:", scalar_broadcast)
print("Вектор:\n", vector_broadcast)
print("Матрица:\n", matrix_broadcast)
print("\nВектор, умноженный на скаляр (транслирование):\n", vector_scaled_broadcast)
print("\nМатрица, умноженная на скаляр (транслирование):\n", matrix_scaled_broadcast)

Скаляр: 2
Вектор:
 [1 2 3]
Матрица:
 [[1 2]
 [3 4]]

Вектор, умноженный на скаляр (транслирование):
 [2 4 6]

Матрица, умноженная на скаляр (транслирование):
 [[2 4]
 [6 8]]


2. Вектор и матрица (транслирование по строкам):        
Чтобы транслировать вектор по столбцам, нам нужно сделать из вектора вектор-столбец с помощью reshape().

In [22]:
matrix_broadcast_2 = np.array([[1, 2, 3], [4, 5, 6]]) # Матрица 2x3
vector_col_broadcast = np.array([100, 200]).reshape((2, 1)) # Вектор-столбец (форма (2, 1))

matrix_plus_col = matrix_broadcast_2 + vector_col_broadcast

print("\nМатрица:\n", matrix_broadcast_2)
print("Вектор-столбец:\n", vector_col_broadcast)
print("\nМатрица + вектор-столбец (транслирование по столбцам):\n", matrix_plus_col)


Матрица:
 [[1 2 3]
 [4 5 6]]
Вектор-столбец:
 [[100]
 [200]]

Матрица + вектор-столбец (транслирование по столбцам):
 [[101 102 103]
 [204 205 206]]


Здесь вектор-столбец [[100], [200]] "транслируется" и "повторяется" для каждого столбца матрицы. То есть к каждому столбцу матрицы прибавляется вектор-столбец.

Преимущества транслирования:

Краткость кода: Не нужно писать циклы для выполнения операций между массивами разных форм. Код становится более лаконичным и читаемым.

Эффективность: Транслирование выполняется очень эффективно, часто быстрее, чем если бы ты писал циклы на Python.

In [23]:
practice_matrix_broadcast = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
practice_vector_row_broadcast = np.array([10, 20, 30])
practice_vector_col_broadcast = np.array([[100], [200], [300]]).reshape((3, 1))
scalar_broadcast = 5

sum_vector = practice_vector_row_broadcast + practice_matrix_broadcast
product = practice_matrix_broadcast * practice_vector_col_broadcast
raznost = practice_matrix_broadcast - scalar_broadcast

print('\nМатрица\n', practice_matrix_broadcast)
print('\nВектор-строка\n', practice_vector_row_broadcast)
print('\nВектор-столбец\n', practice_vector_col_broadcast)
print('\nСумма матрицы и вектор-строка\n', sum_vector)
print('\nПроизведенеи матрицы и вектора-столбца\n', product)
print('\nРазность матрицы и скаляра 5\n', raznost)


Матрица
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Вектор-строка
 [10 20 30]

Вектор-столбец
 [[100]
 [200]
 [300]]

Сумма матрицы и вектор-строка
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

Произведенеи матрицы и вектора-столбца
 [[ 100  200  300]
 [ 800 1000 1200]
 [2100 2400 2700]]

Разность матрицы и скаляра 5
 [[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]


**ufuncs**

Зачем нужны ufuncs?

Скорость: Ufuncs написаны на C и скомпилированы, поэтому они работают на порядки быстрее, чем если бы ты писал аналогичные операции на чистом Python с использованием циклов for. В машинном обучении, где скорость обработки данных критически важна, ufuncs – это настоящее спасение.

Удобство: Ufuncs делают код более лаконичным и читаемым. Вместо того, чтобы писать циклы для обработки каждого элемента массива, ты просто вызываешь ufunc и передаешь ей массив целиком.

Векторизация: Ufuncs позволяют выполнять векторизованные вычисления. Векторизация – это способ программирования, при котором операции применяются сразу к целым массивам данных, а не к отдельным элементам. Векторизованный код обычно гораздо быстрее и эффективнее, чем не векторизованный код с циклами.

Типы ufuncs:

Ufuncs бывают разных типов:

Унарные ufuncs: Выполняют операции над одним массивом. Например:

Математические: np.abs(), np.sqrt(), np.exp(), np.log(), np.sin(), np.cos(), np.tan(), np.floor(), np.ceil(), np.round() и многие другие.

Логические: np.logical_not().

Бинарные ufuncs: Выполняют операции между двумя массивами (поэлементно). Например:

Арифметические: np.add(), np.subtract(), np.multiply(), np.divide(), np.power(), np.mod(). Обрати внимание: операторы +, -, *, /, **, % – это тоже ufuncs в NumPy! Просто более "синтаксически сахарные" версии.

Логические: np.logical_and(), np.logical_or(), np.logical_xor(), np.equal(), np.not_equal(), np.less(), np.greater(), np.less_equal(), np.greater_equal().

Битовые: np.bitwise_and(), np.bitwise_or(), np.bitwise_xor(), np.bitwise_not().

1. Унарные функици

In [24]:
array_ufunc = np.array([-1, 2, -3, 4, -5])

abs_array = np.abs(array_ufunc) # Модуль каждого элемента
sqrt_array = np.sqrt(abs_array) # Квадратный корень из модуля  
exp_array = np.exp(array_ufunc) # Экспонента каждого элемента
sin_array = np.sin(array_ufunc) # Синус каждого элемента
rounded_array = np.round(array_ufunc, decimals=1) # Округление до 1 знака после запятой

print("Исходный массив:\n", array_ufunc)
print("\nМодуль (np.abs):\n", abs_array)
print("\nКвадратный корень (np.sqrt):\n", sqrt_array)
print("\nЭкспонента (np.exp):\n", exp_array)
print("\nСинус (np.sin):\n", sin_array)
print("\nОкругление (np.round):\n", rounded_array)

Исходный массив:
 [-1  2 -3  4 -5]

Модуль (np.abs):
 [1 2 3 4 5]

Квадратный корень (np.sqrt):
 [1.         1.41421356 1.73205081 2.         2.23606798]

Экспонента (np.exp):
 [3.67879441e-01 7.38905610e+00 4.97870684e-02 5.45981500e+01
 6.73794700e-03]

Синус (np.sin):
 [-0.84147098  0.90929743 -0.14112001 -0.7568025   0.95892427]

Округление (np.round):
 [-1  2 -3  4 -5]


2. Бинарные ufuncs:

In [25]:
array_ufunc_1 = np.array([1, 2, 3, 4, 5])
array_ufunc_2 = np.array([6, 7, 8, 9, 10])

sum_arrays = np.add(array_ufunc_1, array_ufunc_2) # Поэлементное сложение
product_arrays = np.multiply(array_ufunc_1, array_ufunc_2) # Поэлементное умножение
power_arrays = np.power(array_ufunc_1, 2) # Возведение в степень (здесь второй массив - скаляр 2, транслируется)
greater_arrays = np.greater(array_ufunc_2, array_ufunc_1) # Поэлементное сравнение "больше" (возвращает массив boolean)

print("\nМассив 1:\n", array_ufunc_1)
print("\nМассив 2:\n", array_ufunc_2)
print("\nСумма (np.add):\n", sum_arrays)
print("\nПроизведение (np.multiply):\n", product_arrays)
print("\nСтепень (np.power):\n", power_arrays)
print("\nСравнение 'больше' (np.greater):\n", greater_arrays)


Массив 1:
 [1 2 3 4 5]

Массив 2:
 [ 6  7  8  9 10]

Сумма (np.add):
 [ 7  9 11 13 15]

Произведение (np.multiply):
 [ 6 14 24 36 50]

Степень (np.power):
 [ 1  4  9 16 25]

Сравнение 'больше' (np.greater):
 [ True  True  True  True  True]


 генерация случайных чисел

В машинном обучении случайные числа играют огромную роль. Вот лишь несколько примеров, где они необходимы:

Инициализация весов нейронных сетей: На старте обучения веса нейросетей задаются случайными значениями. Правильная случайная инициализация очень важна для успешного обучения.

Разбиение данных на обучающую и тестовую выборки: Чтобы честно оценить качество модели, данные случайно разделяют на части для обучения и тестирования.

Перемешивание данных (shuffling): Перед обучением данные часто перемешивают в случайном порядке, чтобы избежать смещений и улучшить обучение.

Алгоритмы случайного поиска (Random Search): Для подбора оптимальных параметров моделей используют случайный перебор вариантов.

Моделирование случайных процессов: В некоторых задачах ML нужно моделировать случайные процессы, например, генерировать случайные траектории или случайные выборки.

NumPy предоставляет мощный подмодуль numpy.random для генерации самых разных случайных чисел и случайных выборок